/**
 * DHRUV E-MITRA SEVA KENDRA - CENTRAL DATA LAYER & I18N
 * Complete verified dataset: Centre details, Services, Rajasthan Gov Forms, Pricing, FAQs, and Translations.
 */

const DHRUV_CONFIG = {
  centreNameEn: "Dhruv E-Mitra Seva Kendra",
  centreNameHi: "ध्रुव ई-मित्र सेवा केंद्र",
  taglineEn: "Your Trusted Digital & Government Citizen Services Partner in Rajasthan",
  taglineHi: "राजस्थान में आपके सभी सरकारी व डिजिटल कार्यों का भरोसेमंद केंद्र",
  address: "Brij Nagar, Bharatpur, Rajasthan, India",
  googleMapsUrl: "https://www.google.com/maps/place/Dhruv+Emitra+seva+kendra/@27.2067169,77.5220438,17z/data=!3m1!4b1!4m6!3m5!1s0x3973a32283868ad3:0xd87d52a2169382d9!8m2!3d27.2067169!4d77.5246241!16s%2Fg%2F11wx33n2_k?hl=en&authuser=0&entry=ttu&g_ep=EgoyMDI2MDkwMi4wIKXMDSoASAFQAw%3D%3D",
  phone: "+91 9079368240",
  phoneRaw: "9079368240",
  whatsapp: "919079368240",
  email: "tarunsinghgunesh@gmail.com",
  timingEn: "Monday - Saturday: 9:00 AM – 7:00 PM (Sunday Available on Call)",
  timingHi: "सोमवार - शनिवार: सुबह 9:00 से शाम 7:00 तक (रविवार कॉल पर उपलब्ध)",
  googleFormApplyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSexE2M_ClTygKtoOGFCzTAL-FQH31nt_Hj5TRGV2b3aGhEsFg/viewform",
  officialEmitra: {
    portal: "https://emitra.rajasthan.gov.in/",
    track: "https://emitra.rajasthan.gov.in/emitra/track",
    services: "https://emitra.rajasthan.gov.in/emitra/services",
    guidelines: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    sso: "https://sso.rajasthan.gov.in/"
  },
  announcement: {
    enabled: true,
    textHi: "📢 महत्वपूर्ण सूचना: राजस्थान छात्रवृत्ति (Scholarship) एवं जन आधार e-KYC के आवेदन शुरू हैं। समय पर कार्य पूर्ण कराएं।",
    textEn: "📢 Important Notice: Rajasthan Scholarship & Jan Aadhaar e-KYC applications are currently active. Apply now at our centre."
  }
};

// 15 Service Categories
const SERVICE_CATEGORIES = [
  { id: "all", nameEn: "All Services", nameHi: "सभी सेवाएं", icon: "fa-list" },
  { id: "certificates", nameEn: "Certificates", nameHi: "प्रमाण पत्र", icon: "fa-certificate" },
  { id: "janaadhaar", nameEn: "Jan Aadhaar", nameHi: "जन आधार सेवाएं", icon: "fa-address-card" },
  { id: "identity", nameEn: "Identity & Documents", nameHi: "पहचान व दस्तावेज", icon: "fa-id-badge" },
  { id: "revenue", nameEn: "Revenue & Land", nameHi: "राजस्व व जमीन (जमाबंदी)", icon: "fa-map-location-dot" },
  { id: "education", nameEn: "Education & Exams", nameHi: "शिक्षा व प्रवेश फॉर्म", icon: "fa-graduation-cap" },
  { id: "employment", nameEn: "Recruitment & Jobs", nameHi: "सरकारी भर्ती व रोजगार", icon: "fa-briefcase" },
  { id: "schemes", nameEn: "Government Schemes", nameHi: "सरकारी योजनाएं", icon: "fa-hands-holding-child" },
  { id: "utility", nameEn: "Electricity & Water Bills", nameHi: "बिजली व पानी बिल", icon: "fa-lightbulb" },
  { id: "recharge", nameEn: "Mobile & DTH Recharge", nameHi: "मोबाइल व डीटीएच", icon: "fa-mobile-screen" },
  { id: "banking", nameEn: "Banking & Financial", nameHi: "बैंकिंग व आधार निकासी (AePS)", icon: "fa-building-columns" },
  { id: "transport", nameEn: "Transport & Driving", nameHi: "परिवहन व ड्राइविंग लाइसेंस", icon: "fa-car" },
  { id: "insurance", nameEn: "Insurance (बीमा)", nameHi: "सुरक्षा व फसल बीमा", icon: "fa-shield-halved" },
  { id: "pension", nameEn: "Pension Services", nameHi: "पेंशन व सत्यापन", icon: "fa-user-check" },
  { id: "forms", nameEn: "Forms & Applications", nameHi: "सरकारी फॉर्म व प्रिंटिंग", icon: "fa-file-lines" },
  { id: "other", nameEn: "Other Citizen Services", nameHi: "अन्य नागरिक सेवाएं", icon: "fa-layer-group" }
];

// Comprehensive Services Dataset (50+ Real Services)
const SERVICES_DATA = [
  {
    id: "caste-obc",
    category: "certificates",
    nameHi: "ओबीसी (OBC) जाति प्रमाण पत्र",
    nameEn: "OBC Caste Certificate",
    department: "Revenue Department, Rajasthan",
    descriptionHi: "राजस्थान राज्य अथवा केंद्रीय प्रारूप में अन्य पिछड़ा वर्ग (OBC) जाति प्रमाण पत्र हेतु ऑनलाइन आवेदन।",
    descriptionEn: "Application for State or Central format OBC caste certificate in Rajasthan.",
    requiredDocs: ["जन आधार कार्ड (Jan Aadhaar)", "आधार कार्ड (Aadhaar)", "राशन कार्ड (Ration Card)", "आय प्रमाण पत्र (Income Proof)", "जमीन की जमाबंदी या पुराना जाति प्रमाण पत्र"],
    processingDays: "5 - 7 कार्य दिवस",
    feeRange: "₹50 - ₹100 (पोर्टल व केंद्र सेवा शुल्क)",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "caste-sc-st",
    category: "certificates",
    nameHi: "एससी / एसटी (SC/ST) जाति प्रमाण पत्र",
    nameEn: "SC / ST Caste Certificate",
    department: "Revenue Department, Rajasthan",
    descriptionHi: "अनुसूचित जाति एवं जनजाति वर्ग के लिए डिजिटल हस्ताक्षरित स्थाई जाति प्रमाण पत्र।",
    descriptionEn: "Digitally signed caste certificate for SC and ST categories.",
    requiredDocs: ["जन आधार कार्ड", "आधार कार्ड", "राशन कार्ड", "पिता का दस्तावेज/पुराना प्रमाण पत्र", "पासपोर्ट फोटो"],
    processingDays: "4 - 7 कार्य दिवस",
    feeRange: "₹50 - ₹100",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "caste-ews",
    category: "certificates",
    nameHi: "ईडब्ल्यूएस (EWS) प्रमाण पत्र",
    nameEn: "Economically Weaker Section (EWS) Certificate",
    department: "Department of Personnel, Rajasthan",
    descriptionHi: "सामान्य वर्ग के आर्थिक रूप से कमजोर नागरिकों के लिए 10% आरक्षण हेतु EWS प्रमाण पत्र।",
    descriptionEn: "EWS certificate for 10% educational and job reservation for general category.",
    requiredDocs: ["जन आधार कार्ड", "आधार कार्ड", "आय प्रमाण पत्र (सक्षम अधिकारी द्वारा सत्यापित)", "भूमि/मकान का विवरण", "शपथ पत्र"],
    processingDays: "7 - 10 कार्य दिवस",
    feeRange: "₹60 - ₹120",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "bonafide-certificate",
    category: "certificates",
    nameHi: "मूल निवास प्रमाण पत्र (Bonafide)",
    nameEn: "Bonafide / Domicile Certificate",
    department: "Revenue Department, Rajasthan",
    descriptionHi: "राजस्थान के मूल निवासी होने का डिजिटल प्रमाण पत्र, जो प्रवेश व सरकारी नौकरियों में अनिवार्य है।",
    descriptionEn: "Official digital Rajasthan residence proof required for education & job recruitments.",
    requiredDocs: ["जन आधार कार्ड", "आधार कार्ड", "10 वर्ष पुराना निवास साक्ष्य (मतदाता सूची/बिजली बिल/जमाबंदी)", "अंतिम शिक्षा प्रमाण पत्र", "फोटो"],
    processingDays: "4 - 7 कार्य दिवस",
    feeRange: "₹50 - ₹100",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "income-certificate",
    category: "certificates",
    nameHi: "आय प्रमाण पत्र (Income Certificate)",
    nameEn: "Income Certificate (1 Page & 4 Page)",
    department: "Finance & Revenue Department",
    descriptionHi: "छात्रवृत्ति, सरकारी योजनाओं व प्रवेश में आय प्रमाणीकरण हेतु निर्धारित प्रारूप।",
    descriptionEn: "Income certificate verification for scholarships, admissions, and government schemes.",
    requiredDocs: ["जन आधार कार्ड", "आधार कार्ड", "नोटरी/गजेटेड अधिकारी द्वारा सत्यापित फॉर्म", "आय साक्ष्य (आईटीआर/वेतन पर्ची/जमाबंदी)"],
    processingDays: "3 - 5 कार्य दिवस",
    feeRange: "₹40 - ₹80",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "jan-aadhaar-ekyc",
    category: "janaadhaar",
    nameHi: "जन आधार e-KYC (सभी सदस्यों की अनिवार्य बायोमेट्रिक)",
    nameEn: "Jan Aadhaar Mandatory e-KYC",
    department: "Planning Department, Rajasthan",
    descriptionHi: "राजस्थान सरकार द्वारा जन आधार के सभी 5 वर्ष से अधिक आयु के सदस्यों की बायोमेट्रिक / OTP e-KYC अनिवार्य।",
    descriptionEn: "Mandatory biometric or OTP-based e-KYC for all Jan Aadhaar card members in Rajasthan.",
    requiredDocs: ["जन आधार कार्ड / रसीद संख्या", "आधार कार्ड", "आधार से लिंक मोबाइल या बायोमेट्रिक फिंगरप्रिंट"],
    processingDays: "तत्काल (Instant Verification)",
    feeRange: "निःशुल्क सरकारी / न्यूनतम ऑपरेटर चार्ज",
    officialUrl: "https://janaadhaar.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "jan-aadhaar-update",
    category: "janaadhaar",
    nameHi: "जन आधार नया सदस्य जोड़ना / संशोधन",
    nameEn: "Jan Aadhaar Member Addition / Update",
    department: "Planning Department, Rajasthan",
    descriptionHi: "जन आधार कार्ड में नाम, जन्मतिथि, बैंक खाता, मोबाइल नंबर, नया बच्चा या बहू का नाम जोड़ना।",
    descriptionEn: "Add family member, update bank accounts, mobile numbers, or corrections in Jan Aadhaar.",
    requiredDocs: ["जन आधार कार्ड", "जोड़े जाने वाले सदस्य का आधार कार्ड", "जन्म प्रमाण पत्र / विवाह प्रमाण पत्र", "बैंक पासबुक"],
    processingDays: "सत्यापन उपरांत (7 - 15 दिन)",
    feeRange: "₹50 - ₹100",
    officialUrl: "https://janaadhaar.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "pan-card-new",
    category: "identity",
    nameHi: "नया पैन कार्ड (PAN Card) ऑनलाइन आवेदन",
    nameEn: "New PAN Card Application",
    department: "Income Tax Department (NSDL / UTIITSL)",
    descriptionHi: "वयस्क एवं अवयस्क (Minor) हेतु नया पैन कार्ड आवेदन। डिजिटल ई-पैन 2 घंटे में व फिजिकल कार्ड पते पर।",
    descriptionEn: "New PAN application for individuals and minors with biometric instant e-PAN facility.",
    requiredDocs: ["आधार कार्ड (Aadhaar Card)", "2 पासपोर्ट साइज फोटो", "हस्ताक्षर", "मोबाइल नंबर"],
    processingDays: "ई-पैन: 2-24 घंटे, फिजिकल कार्ड: 7-10 दिन",
    feeRange: "₹107 (सरकारी शुल्क) + केंद्र सेवा चार्ज",
    officialUrl: "https://www.onlineservices.nsdl.com/",
    popular: true
  },
  {
    id: "pan-correction",
    category: "identity",
    nameHi: "पैन कार्ड संशोधन व डुप्लीकेट (PAN Correction)",
    nameEn: "PAN Card Correction & Reprint",
    department: "Income Tax Department",
    descriptionHi: "खोए हुए पैन कार्ड का पुनः प्रिंट, नाम, पिता का नाम, फोटो व जन्मतिथि संशोधन।",
    descriptionEn: "Reprint lost PAN card or correct name, DOB, father name, photo, and signature.",
    requiredDocs: ["पुराना पैन नंबर / कॉपी", "आधार कार्ड", "संशोधन हेतु सहायक प्रमाण"],
    processingDays: "7 - 12 कार्य दिवस",
    feeRange: "₹110 + सेवा चार्ज",
    officialUrl: "https://www.onlineservices.nsdl.com/",
    popular: false
  },
  {
    id: "voter-id-services",
    category: "identity",
    nameHi: "वोटर आईडी (Voter ID) नया कार्ड / संशोधन / एपिक डाउनलोड",
    nameEn: "Voter ID Card Services & e-EPIC",
    department: "Election Commission of India",
    descriptionHi: "18 वर्ष की आयु पर नया वोटर कार्ड आवेदन (Form 6), पता परिवर्तन व डिजिटल एपिक कार्ड डाउनलोड।",
    descriptionEn: "New voter card registration, address shifting, mobile linking, and digital EPIC print.",
    requiredDocs: ["आधार कार्ड", "जन्म प्रमाण साक्ष्य", "पासपोर्ट फोटो", "परिवार के किसी सदस्य का वोटर नंबर"],
    processingDays: "15 - 25 कार्य दिवस",
    feeRange: "₹40 - ₹60",
    officialUrl: "https://voters.eci.gov.in/",
    popular: false
  },
  {
    id: "land-jamabandi",
    category: "revenue",
    nameHi: "जमाबंदी / खेत की नकल (ई-धरती Apna Khata)",
    nameEn: "Jamabandi / Land Record Nakal (Apna Khata)",
    department: "Revenue Board, Ajmer, Rajasthan",
    descriptionHi: "खेत, जमीन, खसरा नंबर की डिजिटल हस्ताक्षरित जमाबंदी नकल व खाता जानकारी।",
    descriptionEn: "Digitally signed land record Jamabandi copy from Apna Khata Rajasthan portal.",
    requiredDocs: ["जिले व तहसील का नाम", "गांव का नाम", "खाता संख्या या खसरा संख्या या खातेदार का नाम"],
    processingDays: "तत्काल (Instant Print)",
    feeRange: "₹20 - ₹50 (सरकारी टोकन व प्रिंट)",
    officialUrl: "https://apnakhata.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "land-mutation",
    category: "revenue",
    nameHi: "नामांतरण (Mutation) ऑनलाइन आवेदन",
    nameEn: "Land Mutation (Namantran) Application",
    department: "Revenue Department, Rajasthan",
    descriptionHi: "बैनामा (Registry), विरासत या हकत्याग के बाद जमीन का नामांतरण दर्ज कराने हेतु ऑनलाइन अर्जी।",
    descriptionEn: "Online mutation application after sale deed, inheritance, or land division.",
    requiredDocs: ["रजिस्ट्री प्रति / मृत्यु प्रमाण पत्र (विरासत में)", "वर्तमान जमाबंदी", "आधार व जन आधार"],
    processingDays: "15 - 30 कार्य दिवस (पटवारी/तहसील स्तर)",
    feeRange: "₹100 - ₹200",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: false
  },
  {
    id: "electricity-bill",
    category: "utility",
    nameHi: "बिजली बिल भुगतान (JVVNL, AVVNL, JdVVNL)",
    nameEn: "Electricity Bill Payment (Rajasthan Discoms)",
    department: "Energy Department, Rajasthan",
    descriptionHi: "जयपुर डिस्कॉम, अजमेर डिस्कॉम व जोधपुर डिस्कॉम के घरेलू, व्यावसायिक व कृषि बिजली बिल जमा।",
    descriptionEn: "Pay electricity bills for Jaipur, Ajmer, and Jodhpur Discoms with digital instant receipt.",
    requiredDocs: ["के-नंबर (K-Number) या पुराना बिल"],
    processingDays: "तत्काल (Instant Real-time Receipt)",
    feeRange: "बिल राशि (सरकारी नियमानुसार न्यूनतम/शून्य अधिभार)",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "water-bill",
    category: "utility",
    nameHi: "पानी का बिल भुगतान (PHED Rajasthan)",
    nameEn: "Water Bill Payment (PHED Rajasthan)",
    department: "Public Health Engineering Department",
    descriptionHi: "पीएचईडी जन स्वास्थ्य अभियांत्रिकी विभाग के नल कनेक्शन बिल का तत्काल ऑनलाइन भुगतान।",
    descriptionEn: "Instant online payment for PHED drinking water connections with e-receipt.",
    requiredDocs: ["उपभोक्ता संख्या (Consumer ID / Meter No)"],
    processingDays: "तत्काल (Instant)",
    feeRange: "बिल राशि",
    officialUrl: "https://emitra.rajasthan.gov.in/",
    popular: false
  },
  {
    id: "scholarship-sso",
    category: "education",
    nameHi: "उत्तर मैट्रिक छात्रवृत्ति (Post Matric Scholarship - SJED)",
    nameEn: "Post Matric Scholarship Application",
    department: "Social Justice & Empowerment Department",
    descriptionHi: "SC, ST, OBC, EBC, DNT एवं दिव्यांग विद्यार्थियों हेतु कॉलेज एवं उच्च शिक्षा छात्रवृत्ति आवेदन।",
    descriptionEn: "Higher education scholarship applications for SC/ST/OBC/EWS/Specially-abled students.",
    requiredDocs: ["जन आधार कार्ड (e-KYC पूर्ण)", "जाति प्रमाण पत्र", "मूल निवास", "नवीनतम आय प्रमाण पत्र", "फीस रसीद व गत वर्ष अंकतालिका"],
    processingDays: "विभाग के सत्यापन चक्रानुसार",
    feeRange: "₹80 - ₹150",
    officialUrl: "https://sje.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "recruitment-otr",
    category: "employment",
    nameHi: "RPSC व RSSB One Time Registration (OTR)",
    nameEn: "RPSC & RSSB One Time Registration (OTR)",
    department: "Rajasthan Public Service Commission & Staff Selection Board",
    descriptionHi: "राजस्थान की सभी प्रतियोगी परीक्षाओं में आवेदन हेतु अनिवार्य OTR प्रोफाइल का सही पंजीकरण।",
    descriptionEn: "Mandatory One Time Registration on Rajasthan SSO portal for all state competitive exams.",
    requiredDocs: ["आधार कार्ड", "जन आधार कार्ड", "10वीं अंकतालिका", "फोटो व हस्ताक्षर"],
    processingDays: "तत्काल (Instant)",
    feeRange: "₹60 - ₹100",
    officialUrl: "https://sso.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "pension-satyapan",
    category: "pension",
    nameHi: "सामाजिक सुरक्षा पेंशन वार्षिक भौतिक सत्यापन (Biometric/Face)",
    nameEn: "Social Security Pension Annual Verification",
    department: "Social Justice & Empowerment Department",
    descriptionHi: "वृद्धावस्था, विधवा, दिव्यांग पेंशनधारियों का वार्षिक जीवन प्रमाणीकरण (बायोमेट्रिक अथवा फेस एप)।",
    descriptionEn: "Annual life verification for elderly, widow, and disabled pension beneficiaries in Rajasthan.",
    requiredDocs: ["PPO नंबर / जन आधार नंबर", "पेंशनर की स्वयं उपस्थिति (अंगूठा या चेहरा स्कैन)"],
    processingDays: "तत्काल (Instant)",
    feeRange: "₹50 (नियम नियत)",
    officialUrl: "https://ssp.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "pension-new-apply",
    category: "pension",
    nameHi: "नई पेंशन आवेदन (वृद्धावस्था / विधवा / दिव्यांग)",
    nameEn: "New Social Security Pension Application",
    department: "Social Justice & Empowerment Department",
    descriptionHi: "पात्र बुजुर्गों (पुरुष 58+, महिला 55+), निराश्रित महिलाओं एवं विशेष योग्यजन हेतु मासिक पेंशन आवेदन।",
    descriptionEn: "Online application for monthly government pension for senior citizens, widows & disabled.",
    requiredDocs: ["जन आधार कार्ड (बैंक खाता सही लिंक)", "आधार कार्ड", "आयु प्रमाण", "आय प्रमाण पत्र", "दिव्यांगता प्रमाण (यदि लागू)"],
    processingDays: "15 - 30 दिन (स्वीकृति उपरांत)",
    feeRange: "₹70 - ₹120",
    officialUrl: "https://ssp.rajasthan.gov.in/",
    popular: false
  },
  {
    id: "ration-card-services",
    category: "schemes",
    nameHi: "राशन कार्ड सेवा (नया, नाम जोड़ना, NFSA खाद्य सुरक्षा)",
    nameEn: "Ration Card Services (New, Member Add, NFSA)",
    department: "Food & Civil Supplies Department, Rajasthan",
    descriptionHi: "राशन कार्ड में बच्चे/सदस्य का नाम जोड़ना, सुधार, डुप्लीकेट राशन कार्ड व खाद्य सुरक्षा स्थिति जांच।",
    descriptionEn: "Add family members, update details, apply for corrections and NFSA food security checks.",
    requiredDocs: ["पुराना राशन कार्ड", "जन आधार कार्ड", "आधार कार्ड", "जन्म प्रमाण (बच्चे के लिए)"],
    processingDays: "10 - 20 कार्य दिवस",
    feeRange: "₹60 - ₹100",
    officialUrl: "https://food.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "aeps-banking",
    category: "banking",
    nameHi: "आधार से पैसे निकालना व बैलेंस चेक (AePS)",
    nameEn: "AePS Aadhaar Cash Withdrawal & Balance",
    department: "NPCI & Banking Partner Network",
    descriptionHi: "किसी भी बैंक खाते (SBI, PNB, BOB, Gramin Bank आदि) से अंगूठा लगाकर नकद निकासी व बैलेंस जांच।",
    descriptionEn: "Biometric Aadhaar ATM cash withdrawal, balance check, and mini-statement for all Indian banks.",
    requiredDocs: ["आधार नंबर", "बैंक का नाम", "खाताधारक की स्वयं उपस्थिति (फिंगरप्रिंट)"],
    processingDays: "तत्काल (Instant Cash)",
    feeRange: "नियमानुसार निःशुल्क / बैंक दिशा-निर्देश",
    officialUrl: "https://www.npci.org.in/",
    popular: true
  },
  {
    id: "police-character",
    category: "other",
    nameHi: "पुलिस चरित्र प्रमाण पत्र (Police Verification)",
    nameEn: "Police Verification / Character Certificate",
    department: "Rajasthan Police",
    descriptionHi: "नौकरी, सीएसपी/ई-मित्र, सुरक्षा गार्ड, पासपोर्ट आदि हेतु पुलिस चरित्र सत्यापन आवेदन।",
    descriptionEn: "Application for official police character verification certificate across Rajasthan.",
    requiredDocs: ["आधार कार्ड", "जन आधार कार्ड", "पासपोर्ट फोटो", "दो प्रतिष्ठित व्यक्तियों के गवाही पत्र"],
    processingDays: "7 - 14 कार्य दिवस",
    feeRange: "₹260 (सरकारी शुल्क + ई-मित्र चार्ज)",
    officialUrl: "https://police.rajasthan.gov.in/",
    popular: true
  },
  {
    id: "driving-licence",
    category: "transport",
    nameHi: "लर्निंग व ड्राइविंग लाइसेंस आवेदन (Sarathi Parivahan)",
    nameEn: "Learner & Permanent Driving Licence",
    department: "Transport Department, Rajasthan (MoRTH)",
    descriptionHi: "लर्नर लाइसेंस टेस्ट स्लॉट, पक्का लाइसेंस, नवीनीकरण एवं वाहन आरसी सेवाएं।",
    descriptionEn: "Learner licence slot booking, permanent driving licence, and RC renewal support.",
    requiredDocs: ["आधार कार्ड", "10वीं की मार्कशीट (आयु प्रमाण)", "पासपोर्ट फोटो", "मेडिकल फॉर्म 1-A (आवश्यकतानुसार)"],
    processingDays: "स्लॉट व आरटीओ परीक्षा उपरांत",
    feeRange: "सरकारी परिवहन शुल्क + सेवा चार्ज",
    officialUrl: "https://parivahan.gov.in/",
    popular: true
  }
];

// 18 Categories of Authentic Rajasthan Government Forms
const FORMS_DATA = [
  {
    id: "form-caste-state",
    titleHi: "जाति प्रमाण पत्र आवेदन प्रपत्र (राजस्थान राज्य प्रारूप)",
    titleEn: "State Caste Certificate Application Form",
    department: "राजस्व विभाग (Revenue Department)",
    category: "Caste / OBC / EWS",
    categoryKey: "caste",
    descriptionHi: "राजस्थान राज्य सेवाओं व शिक्षण संस्थाओं में आरक्षण हेतु जाति प्रमाण पत्र का आधिकारिक फॉर्म।",
    descriptionEn: "Official state level caste certificate application template for Rajasthan.",
    requiredDocs: "जन आधार, आधार, राशन कार्ड, पिता का जाति साक्ष्य, पटवारी रिपोर्ट",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-caste-central",
    titleHi: "केंद्रीय जाति प्रमाण पत्र प्रारूप (Central OBC / SC / ST)",
    titleEn: "Central Format Caste Certificate Application",
    department: "राजस्व विभाग / DoPT",
    category: "Caste / OBC / EWS",
    categoryKey: "caste",
    descriptionHi: "केंद्र सरकार की नौकरियों (SSC, Railway, Army, Banking) एवं NEET/JEE आदि हेतु फॉर्म।",
    descriptionEn: "Central Government format for jobs & national level competitive admissions.",
    requiredDocs: "राज्य जाति प्रमाण पत्र, जन आधार, आधार, आय प्रमाण पत्र",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-ews-rajasthan",
    titleHi: "ईडब्ल्यूएस (EWS) प्रमाण पत्र आवेदन फॉर्म",
    titleEn: "EWS Certificate Application Form",
    department: "कार्मिक विभाग (DoP Rajasthan)",
    category: "Caste / OBC / EWS",
    categoryKey: "caste",
    descriptionHi: "आर्थिक पिछड़ा वर्ग (सामान्य वर्ग) के 10% आरक्षण हेतु निर्धारित आवेदन फॉर्म व शपथ पत्र।",
    descriptionEn: "Application form and affidavit for Economically Weaker Section reservation.",
    requiredDocs: "जन आधार, आधार कार्ड, आय प्रमाण पत्र, भूमि विवरण, पटवारी रिपोर्ट",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-bonafide",
    titleHi: "मूल निवास प्रमाण पत्र आवेदन प्रपत्र",
    titleEn: "Bonafide / Domicile Certificate Form",
    department: "राजस्व विभाग (Revenue Department)",
    category: "Bonafide / Residence",
    categoryKey: "bonafide",
    descriptionHi: "राजस्थान के मूल निवासी प्रमाण पत्र हेतु 2 उत्तरदायी व्यक्तियों के सत्यापन युक्त फॉर्म।",
    descriptionEn: "Standard application with verification by two responsible citizens/gazetted officers.",
    requiredDocs: "10 वर्ष पुराना निवास साक्ष्य, जन आधार, आधार, शिक्षा प्रमाण पत्र, फोटो",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-income-1page",
    titleHi: "आय प्रमाण पत्र प्रपत्र 'I' (1 पेज प्रारूप)",
    titleEn: "Income Certificate Form 'I' (Single Page)",
    department: "वित्त एवं राजस्व विभाग",
    category: "Revenue Forms",
    categoryKey: "revenue",
    descriptionHi: "सामान्य छात्रवृत्ति, ई-मित्र व कॉलेज सत्यापन हेतु एक पृष्ठीय आय प्रमाण पत्र फॉर्म।",
    descriptionEn: "Single page income verification form for scholarships and admissions.",
    requiredDocs: "सत्यापनकर्ता (गजेटेड/वार्ड पंच/सरपंच) के हस्ताक्षर व मुहर, आधार",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-income-4page",
    titleHi: "आय प्रमाण पत्र प्रपत्र 'K' (4 पेज विस्तृत प्रारूप)",
    titleEn: "Income Certificate Form 'K' (4 Pages Detailed)",
    department: "वित्त एवं राजस्व विभाग",
    category: "Revenue Forms",
    categoryKey: "revenue",
    descriptionHi: "जाति, मूल निवास, ईडब्ल्यूएस एवं उच्च छात्रवृत्तियों में लगने वाला 4 पेज आय फॉर्म।",
    descriptionEn: "Detailed 4-page format with notary, two witness verifications, and family income details.",
    requiredDocs: "नोटरी, 2 राजपत्रित अधिकारियों के हस्ताक्षर, राशन कार्ड, बिजली बिल",
    pdfUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    officialUrl: "https://emitra.rajasthan.gov.in/emitra/report/guideline",
    lastUpdated: "2025"
  },
  {
    id: "form-jan-aadhaar-enrollment",
    titleHi: "जन आधार नामांकन / संशोधन प्रपत्र",
    titleEn: "Jan Aadhaar Enrollment & Amendment Form",
    department: "आयोजना विभाग (Planning Department)",
    category: "Jan Aadhaar",
    categoryKey: "janaadhaar",
    descriptionHi: "जन आधार कार्ड में मुखिया परिवर्तन, नया सदस्य जोड़ने अथवा पारिवारिक विवरण संशोधन का फॉर्म।",
    descriptionEn: "Family head change, member addition, or demographic modification form.",
    requiredDocs: "आधार कार्ड, बैंक पासबुक, विवाह/जन्म प्रमाण पत्र",
    pdfUrl: "https://janaadhaar.rajasthan.gov.in/",
    officialUrl: "https://janaadhaar.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-ration-card-apply",
    titleHi: "राशन कार्ड नया / संशोधन आवेदन फॉर्म",
    titleEn: "Ration Card Application Form (Rural & Urban)",
    department: "खाद्य एवं नागरिक आपूर्ति विभाग",
    category: "Ration Card",
    categoryKey: "ration",
    descriptionHi: "ग्रामीण व शहरी क्षेत्रों में नए राशन कार्ड निर्माण, सदस्य जोड़ने अथवा नाम कटवाने का फॉर्म।",
    descriptionEn: "Application form for new ration cards, deletions, or head modifications.",
    requiredDocs: "पुराना राशन कार्ड / समर्पण पत्र (Surrender Certificate), जन आधार, आधार",
    pdfUrl: "https://food.rajasthan.gov.in/",
    officialUrl: "https://food.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-pension-ssp",
    titleHi: "सामाजिक सुरक्षा पेंशन आवेदन प्रपत्र",
    titleEn: "Social Security Pension Application Form",
    department: "सामाजिक न्याय एवं अधिकारिता विभाग",
    category: "Pension Forms",
    categoryKey: "pension",
    descriptionHi: "मुख्यमंत्री वृद्धजन, एकल नारी (विधवा) एवं विशेष योग्यजन सम्मान पेंशन हेतु ऑफलाइन प्रपत्र।",
    descriptionEn: "Offline application format for Old Age, Widow, and Disability pensions.",
    requiredDocs: "जन आधार, आधार कार्ड, बैंक पासबुक, आयु साक्ष्य, आय घोषणा",
    pdfUrl: "https://ssp.rajasthan.gov.in/",
    officialUrl: "https://ssp.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-palanhar",
    titleHi: "पालनहार योजना नवीन पंजीकरण फॉर्म",
    titleEn: "Palanhar Scheme Registration Form",
    department: "सामाजिक न्याय एवं अधिकारिता विभाग",
    category: "Social Security Forms",
    categoryKey: "social",
    descriptionHi: "अनाथ व निराश्रित बच्चों के पालन-पोषण व शिक्षा हेतु मासिक आर्थिक सहायता का फॉर्म।",
    descriptionEn: "Palanhar scheme form for financial support for orphaned or vulnerable children.",
    requiredDocs: "माता-पिता का मृत्यु प्रमाण/दस्तावेज, बच्चे का अध्ययन प्रमाण पत्र, जन आधार, आधार",
    pdfUrl: "https://sje.rajasthan.gov.in/",
    officialUrl: "https://sje.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-birth-death",
    titleHi: "जन्म एवं मृत्यु प्रमाण पत्र पंजीकरण प्रपत्र",
    titleEn: "Birth & Death Registration Form (Pehchan)",
    department: "आर्थिक एवं सांख्यिकी निदेशालय (Pehchan)",
    category: "Birth / Death",
    categoryKey: "vital",
    descriptionHi: "विलंब से जन्म अथवा मृत्यु पंजीकरण हेतु शपथ पत्र व पंचायत/नगरपालिका जांच प्रपत्र।",
    descriptionEn: "Late birth and death registration affidavit and local enquiry format.",
    requiredDocs: "अस्पताल रिपोर्ट / ग्राम पंचायत रिपोर्ट, माता-पिता का आधार, शपथ पत्र",
    pdfUrl: "https://pehchan.raj.nic.in/",
    officialUrl: "https://pehchan.raj.nic.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-marriage-cert",
    titleHi: "विवाह पंजीयन आवेदन प्रपत्र (Marriage Registration)",
    titleEn: "Marriage Registration Application Form",
    department: "आयोजना विभाग / पहचान पोर्टल",
    category: "Marriage",
    categoryKey: "marriage",
    descriptionHi: "वर एवं वधू के कानूनी विवाह प्रमाण पत्र हेतु संयुक्त आवेदन पत्र व गवाहों का प्रारूप।",
    descriptionEn: "Joint application format with witness details for legal marriage registration.",
    requiredDocs: "वर-वधू की उम्र साक्ष्य, शादी का कार्ड/फोटो, 2 गवाहों के आधार कार्ड",
    pdfUrl: "https://pehchan.raj.nic.in/",
    officialUrl: "https://pehchan.raj.nic.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-labour-card",
    titleHi: "निर्माण श्रमिक (लेबर कार्ड) पंजीकरण फॉर्म",
    titleEn: "Construction Labour Card Application Form",
    department: "श्रम विभाग, राजस्थान (Labour Dept)",
    category: "Labour",
    categoryKey: "labour",
    descriptionHi: "90 दिन निर्माण कार्य प्रमाणीकरण (ठेकेदार/ग्राम सेवक प्रमाण पत्र) एवं श्रमिक डायरी फॉर्म।",
    descriptionEn: "90-day construction work verification certificate by contractor/Panchayat for labour card.",
    requiredDocs: "90 दिन कार्य प्रमाण, जन आधार, आधार, बैंक पासबुक, पासपोर्ट फोटो",
    pdfUrl: "https://labour.rajasthan.gov.in/",
    officialUrl: "https://labour.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-agriculture-tarbandi",
    titleHi: "खेत तारबंदी व कृषि यंत्र अनुदान आवेदन फॉर्म",
    titleEn: "Farm Fencing (Tarbandi) & Equipment Subsidy Form",
    department: "कृषि विभाग, राजस्थान (Rajkisan)",
    category: "Agriculture",
    categoryKey: "agriculture",
    descriptionHi: "आवारा पशुओं से फसल सुरक्षा हेतु तारबंदी अनुदान व पाइपलाइन/यंत्र सब्सिडी फॉर्म।",
    descriptionEn: "Subsidy application form for boundary fencing, pipelines, and farm implements.",
    requiredDocs: "जमाबंदी (6 माह से पुरानी न हो), नक्शा ट्रेस, जन आधार, आधार, बैंक खाता",
    pdfUrl: "https://rajkisan.rajasthan.gov.in/",
    officialUrl: "https://rajkisan.rajasthan.gov.in/",
    lastUpdated: "2025"
  },
  {
    id: "form-police-verification",
    titleHi: "पुलिस चरित्र सत्यापन प्रपत्र (Police Verification Form)",
    titleEn: "Police Verification Application Format",
    department: "राजस्थान पुलिस (Rajasthan Police)",
    category: "Other Government Forms",
    categoryKey: "other",
    descriptionHi: "चरित्र प्रमाण पत्र हेतु दो प्रतिष्ठित व्यक्तियों की गवाही व शपथ प्रारूप।",
    descriptionEn: "Guarantor verification and self-declaration format for police character clearance.",
    requiredDocs: "आधार, जन आधार, 2 पड़ोसियों के पहचान पत्र, पासपोर्ट फोटो",
    pdfUrl: "https://police.rajasthan.gov.in/",
    officialUrl: "https://police.rajasthan.gov.in/",
    lastUpdated: "2025"
  }
];

// Configurable Service Payment Catalogue
const SERVICE_PRICING = [
  { serviceId: "caste-obc", name: "OBC / SC / ST Caste Certificate", deptFee: 50, centreFee: 40, printFee: 10, total: 100, note: "Standard e-Mitra application & print" },
  { serviceId: "bonafide-certificate", name: "Bonafide (Mool Niwas) Certificate", deptFee: 50, centreFee: 40, printFee: 10, total: 100, note: "Complete scan & upload" },
  { serviceId: "caste-ews", name: "EWS Certificate Application", deptFee: 50, centreFee: 50, printFee: 10, total: 110, note: "Includes notary guidance" },
  { serviceId: "income-certificate", name: "Income Certificate Verification", deptFee: 20, centreFee: 40, printFee: 10, total: 70, note: "Affidavit and stamping assistance" },
  { serviceId: "jan-aadhaar-ekyc", name: "Jan Aadhaar Mandatory e-KYC", deptFee: 0, centreFee: 30, printFee: 0, total: 30, note: "Biometric e-KYC per member" },
  { serviceId: "jan-aadhaar-update", name: "Jan Aadhaar Member Addition", deptFee: 30, centreFee: 40, printFee: 10, total: 80, note: "Document verification and upload" },
  { serviceId: "pan-card-new", name: "New PAN Card (NSDL/UTIITSL)", deptFee: 107, centreFee: 73, printFee: 20, total: 200, note: "Includes physical PVC card delivery to home" },
  { serviceId: "land-jamabandi", name: "Apna Khata Jamabandi Nakal", deptFee: 20, centreFee: 20, printFee: 10, total: 50, note: "Digitally signed copy print" },
  { serviceId: "electricity-bill", name: "Electricity / Water Bill Payment", deptFee: 0, centreFee: 20, printFee: 10, total: 30, note: "Official computer receipt generated" },
  { serviceId: "scholarship-sso", name: "Post-Matric Scholarship Form", deptFee: 0, centreFee: 100, printFee: 20, total: 120, note: "Complete marksheet & fee receipt scan" },
  { serviceId: "recruitment-otr", name: "RPSC / RSSB One Time Registration (OTR)", deptFee: 0, centreFee: 70, printFee: 10, total: 80, note: "Careful data entry & verification" },
  { serviceId: "police-character", name: "Police Character Certificate", deptFee: 260, centreFee: 60, printFee: 10, total: 330, note: "Includes Rajasthan Police official fee" },
  { serviceId: "other-consultation", name: "General Form & Online Service", deptFee: 0, centreFee: 50, printFee: 10, total: 60, note: "Standard centre assistance charge" }
];

// FAQs (Hindi & English)
const FAQS_DATA = [
  {
    qHi: "ई-मित्र (e-Mitra) क्या है और ध्रुव ई-मित्र केंद्र कैसे सहायता करता है?",
    qEn: "What is e-Mitra and how does Dhruv E-Mitra assist citizens?",
    aHi: "ई-मित्र राजस्थान सरकार का एकीकृत नागरिक सेवा नेटवर्क है। ध्रुव ई-मित्र सेवा केंद्र (बृज नगर, भरतपुर) एक अधिकृत केंद्र है जहाँ आप सरकारी योजनाओं, प्रमाण पत्रों, बिजली-पानी बिल, छात्रवृत्ति एवं भर्ती फॉर्म का सही व सुरक्षित आवेदन करवा सकते हैं।",
    aEn: "e-Mitra is Rajasthan Government's citizen service platform. Dhruv E-Mitra Seva Kendra is a trusted local citizen service point in Brij Nagar, Bharatpur, Rajasthan, India where citizens can apply for certificates, pay utility bills, submit exam forms, and access welfare schemes without hassles."
  },
  {
    qHi: "आवेदन के लिए कौन-कौन से मूल दस्तावेज अनिवार्य हैं?",
    qEn: "Which basic documents are required for applications?",
    aHi: "राजस्थान के अधिकांश सरकारी कार्यों के लिए जन आधार कार्ड (Jan Aadhaar), आधार कार्ड (Aadhaar), राशन कार्ड एवं मोबाइल नंबर (जो आधार से लिंक हो) प्राथमिक दस्तावेज हैं। प्रमाण पत्र अनुसार विशिष्ट दस्तावेज (जैसे आय, अंकतालिका) अलग से आवश्यक होते हैं।",
    aEn: "For most Rajasthan government applications, Jan Aadhaar card, Aadhaar card, Ration card, and an active mobile number linked to Aadhaar are essential. Specific documents (income, marksheet, land records) vary by service."
  },
  {
    qHi: "मैं अपने आवेदन अथवा लेन-देन की स्थिति कैसे जांच सकता हूँ?",
    qEn: "How can I check my application or transaction status?",
    aHi: "आप हमारी वेबसाइट के '/status' पेज पर जाकर अपना मोबाइल नंबर या टोकन/रसीद नंबर दर्ज कर स्थिति देख सकते हैं। साथ ही आप सीधे आधिकारिक राजस्थान ई-मित्र ट्रैकर लिंक से भी टोकन की स्थिति जान सकते हैं।",
    aEn: "Visit our '/status' page and enter your registered mobile number or Receipt/Token ID. We also provide direct redirection to the official Rajasthan e-Mitra tracking portal."
  },
  {
    qHi: "क्या सेवा शुल्क (Charges) पारदर्शी और नियत हैं?",
    qEn: "Are service charges transparent and fixed?",
    aHi: "हाँ, हमारे केंद्र पर सरकारी टोकन शुल्क और केंद्र सेवा शुल्क पूरी तरह पारदर्शी हैं। भुगतान के उपरांत डिजिटल रसीद (Invoice) प्रदान की जाती है जिसमें कोई छिपा शुल्क नहीं होता।",
    aEn: "Yes, all official department fees and centre service charges are completely transparent and published in our catalogue. You receive a digital receipt for every payment."
  },
  {
    qHi: "क्या मैं अपनी डिजिटल रसीद (Receipt) डाउनलोड कर सकता हूँ?",
    qEn: "Can I download or reprint my digital receipt?",
    aHi: "हाँ! भुगतान के तुरंत बाद आपको A4 आकार की डिजिटल रसीद मिलती है जिसे आप PDF में डाउनलोड, प्रिंट या सीधे WhatsApp पर प्राप्त कर सकते हैं। '/receipt' पेज पर रसीद नंबर डालकर कभी भी पुनः प्राप्त किया जा सकता है।",
    aEn: "Yes! Immediately upon payment confirmation, an A4 digital receipt is generated with download, print, and WhatsApp sharing options. You can also look it up anytime on '/receipt'."
  },
  {
    qHi: "क्या मैं सीधे WhatsApp या फोन पर संपर्क कर सकता हूँ?",
    qEn: "Can I contact the centre directly on WhatsApp or Call?",
    aHi: "हाँ, आप +91 9079368240 पर कॉल कर सकते हैं अथवा वेबसाइट पर लगे WhatsApp बटन से सीधे चैट शुरू कर सकते हैं। हमारी टीम तुरंत सहायता करती है।",
    aEn: "Yes, you can call us at +91 9079368240 or tap the WhatsApp button for instant assistance regarding documents, status, or queries."
  }
];

// Bilingual UI Text Dictionary
const I18N = {
  hi: {
    siteTitle: "ध्रुव ई-मित्र सेवा केंद्र",
    govBadge: "राजस्थान सरकार ई-मित्र सेवा सहायता केंद्र",
    navHome: "होम",
    navServices: "सेवाएं",
    navForms: "फॉर्म व गाइडलाइन",
    navStatus: "स्थिति जांचें",
    navPayment: "शुल्क भुगतान",
    navReceipt: "रसीद खोजें",
    navContact: "संपर्क",
    navApply: "ऑनलाइन आवेदन",
    heroHeadline: 'आपके हर <span class="text-3d-gradient">डिजिटल काम</span> का भरोसेमंद केंद्र',
    heroSub: "ध्रुव ई-मित्र सेवा केंद्र — राजस्थान सरकार की नागरिक सेवाएं, ऑनलाइन आवेदन, प्रमाण पत्र, बिजली बिल, फॉर्म एवं प्रमाणिक सहायता।",
    exploreServices: "सेवाएं देखें",
    checkStatusBtn: "स्थिति जांचें",
    callNow: "कॉल करें",
    whatsappBtn: "व्हाट्सएप करें",
    getDirections: "रास्ता देखें (Maps)",
    trust1: "सरकारी सेवा सहायता",
    trust2: "त्वरित ऑनलाइन आवेदन",
    trust3: "पारदर्शी शुल्क व्यवस्था",
    trust4: "डिजिटल रसीद उपलब्ध",
    trust5: "स्थानीय विश्वसनीय केंद्र",
    popularServices: "लोकप्रिय सेवाएं",
    viewAllServices: "सभी 50+ सेवाएं देखें →",
    whyChooseTitle: "ध्रुव ई-मित्र ही क्यों चुनें?",
    howItWorksTitle: "काम कैसे होता है? आसान 4 चरण",
    step1Title: "सेवा चुनें",
    step1Desc: "आवश्यक सेवा और आवश्यक दस्तावेजों की सूची देखें।",
    step2Title: "दस्तावेज जमा करें",
    step2Desc: "केंद्र पर आएं अथवा व्हाट्सएप/ऑनलाइन फॉर्म से सुरक्षित भेजें।",
    step3Title: "सुरक्षित भुगतान",
    step3Desc: "पारदर्शी सरकारी व केंद्र शुल्क का UPI/ऑनलाइन भुगतान करें।",
    step4Title: "रसीद व कार्य प्राप्ति",
    step4Desc: "डिजिटल रसीद पाएं और कार्य पूर्ण होने पर प्रमाण पत्र प्राप्त करें।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल (FAQ)",
    searchPlaceholder: "सेवा खोजें (उदा. जाति, मूल निवास, जन आधार, बिजली बिल)...",
    searchFormsPlaceholder: "आप कौन-सा सरकारी फॉर्म ढूंढ रहे हैं? (उदा. जाति, राशन कार्ड, आय)...",
    footerDisclaimer: "यह एक स्वतंत्र अधिकृत ई-मित्र सेवा केंद्र की वेबसाइट है। सरकारी सेवाएं संबंधित विभागीय नियमों व आधिकारिक पोर्टल उपलब्धता के अधीन हैं।",
    officialEmitraLinkText: "राजस्थान सरकार का आधिकारिक ई-मित्र पोर्टल देखें →",
    copyright: "© 2026 ध्रुव ई-मित्र सेवा केंद्र, बृज नगर, भरतपुर, राजस्थान, भारत। सभी अधिकार सुरक्षित।"
  },
  en: {
    siteTitle: "Dhruv E-Mitra Seva Kendra",
    govBadge: "Authorized Rajasthan E-Mitra Citizen Service Assistance",
    navHome: "Home",
    navServices: "Services",
    navForms: "Forms & Guidelines",
    navStatus: "Track Status",
    navPayment: "Pay Charges",
    navReceipt: "Find Receipt",
    navContact: "Contact",
    navApply: "Apply Online",
    heroHeadline: 'Your Most Trusted Center for Every <span class="text-3d-gradient">Digital Service</span>',
    heroSub: "Dhruv E-Mitra Seva Kendra — Rajasthan Government & Citizen Services, Online Applications, Certificates, Bill Payments, Forms and More.",
    exploreServices: "Explore Services",
    checkStatusBtn: "Check Status",
    callNow: "Call Now",
    whatsappBtn: "WhatsApp Us",
    getDirections: "Get Directions",
    trust1: "Govt Service Assistance",
    trust2: "Fast Online Applications",
    trust3: "Transparent Charges",
    trust4: "Digital Receipt Available",
    trust5: "Local Dedicated Support",
    popularServices: "Popular Services",
    viewAllServices: "View All 50+ Services →",
    whyChooseTitle: "Why Choose Dhruv E-Mitra?",
    howItWorksTitle: "How It Works? 4 Simple Steps",
    step1Title: "Choose Service",
    step1Desc: "Find your required service and verify document checklist.",
    step2Title: "Submit Documents",
    step2Desc: "Visit centre or submit securely via WhatsApp / online form.",
    step3Title: "Pay Securely",
    step3Desc: "Pay transparent government and centre charges via UPI / Online.",
    step4Title: "Receive Receipt & Delivery",
    step4Desc: "Get instant digital receipt and track until certificate completion.",
    faqTitle: "Frequently Asked Questions (FAQ)",
    searchPlaceholder: "Search services (e.g. Caste, Bonafide, Jan Aadhaar, Electricity)...",
    searchFormsPlaceholder: "Which government form are you looking for? (e.g. Caste, Ration Card, Income)...",
    footerDisclaimer: "Independent e-Mitra service centre website. Government services are subject to applicable department rules and official portal availability.",
    officialEmitraLinkText: "Visit Official Rajasthan Government e-Mitra Portal →",
    copyright: "© 2026 Dhruv E-Mitra Seva Kendra, Brij Nagar, Bharatpur, Rajasthan, India. All Rights Reserved."
  }
};
